### ISSUE TITLE
Aparece o ano em transações realizadas em anos anteriores?

### ISSUE THREAD

**Issue by xthiago** [fitus/nubank-export#3]
Nas transações realizadas nesse ano somente o dia e mês são exibidos. 

Pretendo colocar uma tratativa para exportarmos a data corretamente.

Caso apareça, com 2 ou 4 digitos?

**Comment by dkamioka** [comment]
Boa, na verdade é complicado, porque não sei como vem o dado, eu repasso
como texto direto sem tratar. Eu não tenho dados de 2014 para saber também
:(

Em dom, 9 de ago de 2015 00:18, Thiago Rodrigues notifications@github.com
escreveu:

**Comment by gabrielrcouto** [comment]
Sim, aparece e somente com 2 dígitos.

![image](https://cloud.githubusercontent.com/assets/2197005/9154992/d0e3d8ba-3e7e-11e5-88f7-b6d0ff5cc71c.jpg)
![image](https://cloud.githubusercontent.com/assets/2197005/9154993/d11b4142-3e7e-11e5-985c-2dc1e8a63825.jpg)

**Comment by gabrielrcouto** [comment]
No caso da lista de despesas, não aparece, será necessário sempre olhar o campo de período. Tirei um print para mostrar a mudança de ano.
![image](https://cloud.githubusercontent.com/assets/2197005/9155006/b08f791a-3e7f-11e5-9fbb-d107c87c85bc.jpg)

**Comment by thomasgroch** [comment]
Gostei muito da iniciativa parabens a todos envolvidos.
Como ninguém tocou nesse tópico a um bom tempo segue uma pequena gambiarra que eu fiz para adicionar o ano no final da data.

Embora ainda não esteja estável nem mesmo é uma boa maneira de abordar o problema.

`https://pastebin.com/rJqrwuQr`

Mantive as mensagem de debug se alguém quiser continuar a lógica

**Comment by dkamioka** [comment]
Este projeto estava meio abandonado, mas acabei de fazer o merge de um pull request que coloca as tags em csv separados por um "|".

@thomasgroch poderia fazer um pull request em cima dessa última alteração?

Obrigado galera!

**Comment by pedrommone** [comment]
Agora é possível exportar direto do nubank, dentro de cada fatura.

![screen shot 2017-09-16 at 22 22 27](https://user-images.githubusercontent.com/1310609/30517180-9ab5094a-9b2d-11e7-9813-acd1e5f59839.png)

**Comment by dkamioka** [comment]
Então perdeu a necessidade galera! :)


[image: photo]

Diogo Kamioka
Agile and DevOps Specialist
http://diogo.kamioka.com.br // diogo.kamioka@gmail.com // Skype: dkamioka
<#>
<https://twitter.com/dkamioka> <https://www.linkedin.com/in/dkamioka/>
<https://medium.com/@dkamioka/thats-the-challenge-7023398817cc?source=rss-6f3a454ad4c6------2>
Latest
item: That's the challenge! ;)
<https://medium.com/@dkamioka/thats-the-challenge-7023398817cc?source=rss-6f3a454ad4c6------2>



*Farofitus** - Diogo Key Kamioka*
*UFSCar** - Universidade Federal de São Carlos*
*BCC04** - Bacharelado em Ciência da Computação*



*mobile: +55 11 8729 2929 diogo.kamioka@gmail.com <diogo.kamioka@gmail.com>
São Paulo/SP - Brazil website <http://www.kamioka.com.br/dkey> | twitter
<http://www.twitter.com/dkamioka> | LinkedIn
<http://www.linkedin.com/in/dkamioka>*

**Comment by xthiago** [comment]
Não perdeu a utilidade. A exportação feita através da interface do Nubank não inclui as `tags` no CSV. Além disso, não é possível exportar a fatura atual enquanto a mesma não é fechada.
